# Generated by Django 6.0.2 on 2026-03-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectList',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('can_take_case', models.CharField(blank=True, max_length=1, null=True)),
                ('project_level', models.CharField(blank=True, max_length=1, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True)),
                ('topic', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'project_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.UUIDField(primary_key=True, serialize=False)),
                ('role_type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'role',
                'managed': False,
            },
        ),
    ]
