# Generated by Django 6.0.2 on 2026-04-07 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_projectlist_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.TextField(unique=True)),
                ('resource_id', models.TextField(blank=True, null=True)),
                ('sync_token', models.TextField(blank=True, null=True)),
                ('expiration', models.BigIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'calendar_sync_state',
            },
        ),
    ]
